
# RocketMQAutoConfiguration
# RocketMQProperties
rocketmq:
  name-server: "localhost:9876"
  access-channel: "LOCAL"
  producer:
    group: "userProducerGroup"
#    namespace: "userNamespace"
#    send-message-timeout: 3000
    enable-msg-trace: true
#    instance-name: "DEFAULT"
  pull-consumer:
    group: "userConsumerGroup"
#    namespace: "userNamespace"
    topic: "userTopicName"
#    message-model: "CLUSTERING"
#    selector-type: "TAG"
#    selector-expression: "*"
#    pull-batch-size: 10
    enable-msg-trace: true
#    instance-name: "DEFAULT"
  consumer:
    group: "userConsumerGroup"
#    namespace: "userNamespace"
    topic: "userTopicName"
    # 推送消费者的监听器，默认开启
#    listeners:
#      { "userConsumerGroup": { "userTopicName": false } }
#    message-model: "CLUSTERING"
#    selector-type: "TAG"
#    selector-expression: "*"
#    pull-batch-size: 10
    enable-msg-trace: true
#    instance-name: "DEFAULT"
