
spring:
  application:
    name: observability-spring-boot-starter-example
  profiles:
    active: dev

server:
  port: 8383
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accesslog: # https://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Access_Logging
      enabled: true
      pattern: "%{begin:yyyy-MM-dd HH:mm:ss.SSS}t  '%h %l %u' [%I] '\"%r\" %s %bB' '%Dms %Fms'"
      prefix: tomcat_access
      directory: "/opt/logs/${spring.application.name}/"

#logging:
#  level:
#    root: info
#  file:
#    name:

management:
  # ManagementServerProperties
  server:
    port: 38081
    base-path: ""
  endpoints:
    # WebEndpointProperties
    web:
      exposure:
        include: "*"
        exclude: "metrics,heapdump,threaddump"
      base-path: ""
#      base-path: "/actuator"
      # Customizing the Management Endpoint Paths
      path-mapping:
        "prometheus": "metrics"
  # MetricsProperties
  metrics:
    use-global-registry: true
#    enable:
#      heapdump: false
#      threaddump: false
    tags:
      application: "${spring.application.name}"
    export:
      # JmxProperties
      jmx:
        enabled: true
        domain: "metrics"
        step: 1m
      # PrometheusProperties
      prometheus:
        enabled: true
#        descriptions: true
#        pushgateway:
#          enabled: false
#          push-rate: 1m
#          shutdown-operation: push
        step: 1m
