

spring:
  application:
    name: autowire-bean-with-diff-impl-conditional-on-property

# 会议服务实现
meeting:
  service: edge
#  service: cloud

logging:
  charset:
    console: UTF-8
    file: UTF-8
#  config: "classpath:org/springframework/boot/logging/log4j2/log4j2-file.xml"
  file:
    path: "/var/log"
  level:
    root: info
#  logback:
#    rollingpolicy:
#      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
#      clean-history-on-start: false
#      max-file-size: 10MB
#      total-size-cap: 0MB
#      max-history: 14

